# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gaitin 
name: 个人博客 
email: 706182625@qq.com
location: Beijing 
company:  Beijing Syswin Interconnected technology
company_url: http://www.toon.mobi/
github_url: https://github.com/Gaitin 
description: 个人博客
favicon: favicon.png
repository: https://github.com/Gaitin/gaitin.github.io 

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. https://gaitin.github.io/
url:https://gaitin.github.io/

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java,MySQL, Design Patterns]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, Boostrap,React,Vue,Redux,dva,Weex,antd]
skill_mobile_app_keywords: [React Native, Sketch UI Desgin]
